# Exported from Render on 2025-12-12T15:21:39Z
version: "1"
projects:
- name: sunday_library_timesheet
  environments:
  - name: Production
    databases:
    - name: sunday_library
      databaseName: sunday_library
      user: sunday_library_user
      plan: free
      region: virginia
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "18"
